name: atproto_dart
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  characters: ^1.4.0
  cli_util: ^0.4.2
  github: ^9.12.0
  html: ^0.15.5
  http: ^1.2.1
  intl: ^0.19.0
  lexicon: ^0.2.0
  mime: ^2.0.0
  pubspec: ^2.3.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  melos: ^6.0.0
  import_sorter: ^4.6.0
